# Dataset configuration
# Network configuration
backbone: resnet50
use_bottleneck: true

# Transfer loss configuration
transfer_loss: cfd
transfer_loss_weight: 10.0

# Training configuration
n_epoch: 20
batch_size: 32

# Optimizer configuration
lr: 0.001
weight_decay: 0.0005
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9


# CFD loss specific configuration
cfd_alpha: 0.5  # Weight for amplitude in CFD loss
cfd_beta: 0.5   # Weight for phase in CFD loss
t_batchsize: 2048 # Sample network batch size

# Others
seed: 1
num_workers: 6
