# Network configuration
backbone: resnet50

# Transfer loss configuration
transfer_loss: cfd
transfer_loss_weight: 1.0

# Training configuration
n_iter_per_epoch: 500
n_epoch: 20

# Optimizer configuration
lr: 3e-3
weight_decay: 5e-4
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9


# CFD loss specific configuration
cfd_alpha: 0.5  # Weight for amplitude in CFD loss
cfd_beta: 0.5   # Weight for phase in CFD loss
t_batchsize: 2048 # Sample network batch size

# Others
seed: 1
num_workers: 6
